// Idaho shooting locations database with detailed metadata
// Extracted from intel page for proper data architecture

export const shootingLocations = [
  // Designated Public Ranges - Idaho Fish & Game Managed
  {
    name: "Black's Creek Public Shooting Range",
    type: "Public Range",
    description: "Idaho's premier public shooting facility managed by Idaho Fish & Game. Features multiple disciplines with excellent safety infrastructure and community programs.",
    address: "2420 E Kuna-Mora Rd, Kuna, ID 83634",
    coordinates: "43.4629° N, 116.1559° W",
    lat: 43.4629,
    lng: -116.1559,
    access: "Free Public Access",
    hours: "Wed-Sun: 9AM-5PM (Closed Mon-Tue)",
    restrictions: "Mandatory safety briefing for first-time visitors. No steel targets during high fire danger. Lead ammunition restrictions.",
    amenities: ["100-yard rifle range", "200-yard rifle range", "25-yard pistol range", "Shotgun pattern board", "Restrooms", "Parking for 50+ vehicles", "Covered shooting benches", "Target stands provided"],
    distanceFromBoise: 18.5,
    difficulty: "Easy",
    category: "Public Range",
    verified: true,
    elevation: 2654,
    bestWindConditions: "Early morning (7-10 AM)",
    lastUpdated: "2025-01-15",
    weatherPriority: "high"
  },
  {
    name: "Independence Indoor Shooting",
    type: "Indoor Range", 
    description: "Premier indoor facility featuring climate-controlled environments and advanced ventilation. Perfect for precision work and training regardless of weather.",
    address: "2701 S Vista Ave, Boise, ID 83705",
    coordinates: "43.5684° N, 116.2494° W",
    lat: 43.5684,
    lng: -116.2494,
    access: "$25 lane rental",
    hours: "Mon-Sat: 10AM-9PM, Sun: 10AM-6PM",
    restrictions: "Eye and ear protection required. Range ammunition only. No steel-core or armor-piercing. Age restrictions for unsupervised minors.",
    amenities: ["25-yard climate-controlled lanes", "Advanced ventilation system", "Target systems", "Rental firearms available", "Pro shop", "Gunsmith services", "Training classes", "Private instruction"],
    distanceFromBoise: 3.2,
    difficulty: "Easy", 
    category: "Indoor Range",
    verified: true,
    elevation: 2785,
    bestWindConditions: "N/A - Indoor facility",
    lastUpdated: "2025-01-14",
    weatherPriority: "low"
  },
  {
    name: "George Nourse Park Range",
    type: "Municipal Range",
    description: "City of Boise managed outdoor range in east Boise. Well-maintained facility with regular community events and training programs.",
    address: "901 N Collister Dr, Boise, ID 83703",
    coordinates: "43.6398° N, 116.2089° W", 
    lat: 43.6398,
    lng: -116.2089,
    access: "Free with Boise residency, $10 non-resident",
    hours: "Daylight hours, check seasonal schedule",
    restrictions: "Boise city limits. Safety rules strictly enforced. No rapid fire. Supervised ranges only.",
    amenities: ["50-yard rifle range", "25-yard pistol range", "Benches and target stands", "Parking", "Restrooms nearby", "Regular safety officers"],
    distanceFromBoise: 5.8,
    difficulty: "Easy",
    category: "Municipal Range", 
    verified: true,
    elevation: 2812,
    bestWindConditions: "Morning hours (6-10 AM)",
    lastUpdated: "2024-12-28",
    weatherPriority: "medium"
  },
  // BLM Dispersed Shooting Areas
  {
    name: "Snake River Birds of Prey Area",
    type: "BLM Dispersed",
    description: "Expansive BLM area with multiple established shooting positions. Excellent natural backstops and varied terrain for different disciplines.",
    address: "Kuna-Swan Falls Rd, south of Kuna, ID",
    coordinates: "43.2661° N, 116.4170° W",
    lat: 43.2661,
    lng: -116.4170,
    access: "Free BLM Access",
    hours: "Sunrise to sunset year-round",
    restrictions: "Wildlife closure Feb 1 - July 31 in nesting areas. Fire restrictions May-October. Pack out all trash. No glass targets. 150-yard minimum from roads.",
    amenities: ["Natural rock backstops", "Multiple shooting positions", "Varied distances", "Desert environment", "Established access roads", "Popular with local clubs"],
    distanceFromBoise: 28.3,
    difficulty: "Moderate",
    category: "BLM Land",
    verified: true,
    elevation: 2340,
    bestWindConditions: "Early morning, late evening",
    lastUpdated: "2025-01-08",
    weatherPriority: "high"
  },
  {
    name: "Table Rock Area - Boise Foothills", 
    type: "BLM Dispersed",
    description: "Popular foothills location with excellent elevation and backstops. Close to Boise but can be busy on weekends. Multiple established positions.",
    address: "Table Rock Rd, Boise, ID 83712",
    coordinates: "43.5949° N, 116.1429° W",
    lat: 43.5949,
    lng: -116.1429,
    access: "Free BLM Access",
    hours: "Sunrise to sunset, year-round",
    restrictions: "Respect private property boundaries. Fire restrictions apply. No shooting within 150 yards of roads or trails. Pack out all trash.",
    amenities: ["Natural hillside backstops", "Multiple positions", "Easy 2WD access", "Scenic mountain views", "Close to Boise", "Popular area"],
    distanceFromBoise: 12.1,
    difficulty: "Easy",
    category: "BLM Land",
    verified: true,
    elevation: 3245,
    bestWindConditions: "Morning hours (6-10 AM)",
    lastUpdated: "2024-12-15",
    weatherPriority: "high"
  },
  {
    name: "Lucky Peak Area - East Boise",
    type: "Forest Service",
    description: "Forest Service land near Lucky Peak Dam with established shooting areas. Higher elevation provides cooler temperatures and less wind.",
    address: "Lucky Peak Dam Rd, Boise, ID 83716",
    coordinates: "43.5234° N, 116.0654° W", 
    lat: 43.5234,
    lng: -116.0654,
    access: "Free Forest Service Access",
    hours: "Sunrise to sunset, seasonal closures possible",
    restrictions: "Forest Service regulations. Fire restrictions May-September. No target shooting within 150 yards of water. Seasonal wildlife closures possible.",
    amenities: ["Mountain backstops", "Cooler temperatures", "Less crowded", "Forest setting", "Multiple positions", "Good for long-range"],
    distanceFromBoise: 16.7,
    difficulty: "Moderate",
    category: "Forest Service",
    verified: true,
    elevation: 3890,
    bestWindConditions: "Early morning, evening",
    lastUpdated: "2024-11-30",
    weatherPriority: "high"
  },
  {
    name: "Emmett Area - Squaw Creek",
    type: "BLM Dispersed",
    description: "Northern Treasure Valley location with excellent backstops and less pressure. Good for those seeking quieter shooting opportunities.",
    address: "Squaw Creek Rd, near Emmett, ID 83617",
    coordinates: "43.8456° N, 116.4823° W",
    lat: 43.8456,
    lng: -116.4823,
    access: "Free BLM Access",
    hours: "Sunrise to sunset year-round",
    restrictions: "BLM regulations apply. Fire restrictions in summer. Pack out trash. No glass targets. Be aware of private property boundaries.",
    amenities: ["Natural backstops", "Less crowded", "Good access road", "Multiple positions", "Varied terrain", "Northern valley views"],
    distanceFromBoise: 32.5,
    difficulty: "Easy",
    category: "BLM Land",
    verified: false,
    elevation: 2456,
    bestWindConditions: "Morning hours",
    lastUpdated: "2024-10-22",
    weatherPriority: "medium",
    needsVerification: true
  },
  // Remote/Advanced Areas
  {
    name: "Owyhee Mountains - Jump Creek",
    type: "Remote BLM",
    description: "Remote high-desert location requiring preparation and 4WD access. Excellent for long-range shooting with minimal interference.",
    address: "Jump Creek Rd, Owyhee County, ID",
    coordinates: "43.0234° N, 116.7892° W",
    lat: 43.0234,
    lng: -116.7892,
    access: "Free BLM Access (4WD required)",
    hours: "Sunrise to sunset, weather dependent",
    restrictions: "4WD vehicle required. Inform others of plans. Carry emergency supplies. Fire restrictions critical. Remote area - no services.",
    amenities: ["Excellent long-range backstops", "Minimal crowds", "High-desert environment", "Multiple canyons", "Advanced shooting opportunities"],
    distanceFromBoise: 67.2,
    difficulty: "Difficult", 
    category: "Remote/4WD",
    verified: false,
    elevation: 4123,
    bestWindConditions: "Early morning",
    lastUpdated: "2024-09-18",
    weatherPriority: "high",
    needsVerification: true
  },
  {
    name: "CJ Strike Reservoir Area",
    type: "BLM Dispersed",
    description: "Southwestern Idaho location with good backstops and water access nearby. Popular with camping shooters and multi-day enthusiasts.",
    address: "CJ Strike Dam Rd, Bruneau, ID 83604",
    coordinates: "42.9567° N, 115.9234° W", 
    lat: 42.9567,
    lng: -115.9234,
    access: "Free BLM Access",
    hours: "24/7 access, daylight shooting only",
    restrictions: "BLM regulations. Seasonal fire restrictions. Water safety regulations near reservoir. Pack out all trash.",
    amenities: ["Natural backstops", "Water access nearby", "Camping opportunities", "Less crowded", "Good for extended trips"],
    distanceFromBoise: 89.4,
    difficulty: "Moderate",
    category: "BLM Land",
    verified: false,
    elevation: 2698,
    bestWindConditions: "Morning and evening",
    lastUpdated: "2024-08-15",
    weatherPriority: "medium",
    needsVerification: true
  },
  // Northern Areas
  {
    name: "Payette National Forest - Banks",
    type: "Forest Service",
    description: "Mountain forest location with cooler temperatures and excellent backstops. Seasonal access with potential snow closure in winter.",
    address: "Banks-Lowman Rd, Banks, ID 83602",
    coordinates: "44.0891° N, 116.1123° W",
    lat: 44.0891,
    lng: -116.1123,
    access: "Free Forest Service Access",
    hours: "Sunrise to sunset, seasonal closures",
    restrictions: "Forest Service regulations. Seasonal road closures Nov-May. Fire restrictions summer. No target shooting within 150 yards of roads/trails/water.",
    amenities: ["Mountain environment", "Cooler temperatures", "Forest setting", "Good backstops", "Less crowded", "Scenic area"],
    distanceFromBoise: 52.3,
    difficulty: "Moderate",
    category: "Forest Service",
    verified: false,
    elevation: 4567,
    bestWindConditions: "Sheltered, variable",
    lastUpdated: "2024-07-20",
    weatherPriority: "high",
    needsVerification: true
  },
  {
    name: "Caldwell - Deer Flat Area",
    type: "BLM Dispersed",
    description: "Western Treasure Valley location with good access and established positions. Popular with Nampa and Caldwell area shooters.",
    address: "Lake Ave, near Caldwell, ID 83607",
    coordinates: "43.6234° N, 116.7345° W", 
    lat: 43.6234,
    lng: -116.7345,
    access: "Free BLM Access",
    hours: "Sunrise to sunset year-round",
    restrictions: "BLM regulations. Respect wildlife refuge boundaries. Fire restrictions apply. No shooting near water areas.",
    amenities: ["Established positions", "Good access road", "Western valley location", "Less pressure than eastern areas"],
    distanceFromBoise: 28.9,
    difficulty: "Easy",
    category: "BLM Land",
    verified: false,
    elevation: 2298,
    bestWindConditions: "Morning hours",
    lastUpdated: "2024-06-12",
    weatherPriority: "medium",
    needsVerification: true
  },
  // Central Idaho - Advanced
  {
    name: "Boise National Forest - Pine",
    type: "Forest Service",
    description: "High-elevation forest location offering cooler shooting conditions and excellent long-range opportunities. Requires mountain driving skills.",
    address: "Pine-Featherville Rd, Pine, ID 83647",
    coordinates: "43.4523° N, 115.2167° W",
    lat: 43.4523,
    lng: -115.2167,
    access: "Free Forest Service Access",
    hours: "Sunrise to sunset, seasonal access",
    restrictions: "Mountain road access. Seasonal snow closures. Forest Service regulations. Fire restrictions critical. High elevation conditions.",
    amenities: ["High elevation", "Cooler conditions", "Long-range opportunities", "Mountain scenery", "Advanced terrain", "Less accessible"],
    distanceFromBoise: 78.6,
    difficulty: "Difficult",
    category: "Forest Service",
    verified: false,
    elevation: 5234,
    bestWindConditions: "Variable mountain conditions",
    lastUpdated: "2024-05-30",
    weatherPriority: "high",
    needsVerification: true
  }
]

// High-priority weather monitoring locations for ticker display - OUTDOOR ONLY
export const featuredWeatherLocations = [
  { name: "Black's Creek Public Shooting Range", lat: 43.4629, lng: -116.1559 },
  { name: "Snake River Birds of Prey Area", lat: 43.2661, lng: -116.4170 },
  { name: "Table Rock Area - Boise Foothills", lat: 43.5949, lng: -116.1429 },
  { name: "Lucky Peak Area - East Boise", lat: 43.5234, lng: -116.0654 },
  { name: "Owyhee Mountains - Jump Creek", lat: 43.0234, lng: -116.7892 }
]

// Calculate real stats from location data - honest MVP numbers
export function getLocationStats() {
  return {
    totalLocations: shootingLocations.length,
    verifiedLocations: shootingLocations.filter(l => l.verified).length,
    publicAreas: shootingLocations.filter(l => l.category.includes("Public") || l.category.includes("BLM")).length,
    milesOfLand: 850, // Estimated acres of shooting land in Idaho (BLM + Forest Service)
    publicClubs: shootingLocations.filter(l => l.category === "Public Range").length,
    privateClubs: shootingLocations.filter(l => l.category === "Private Club").length
  }
}